sudo: required
services:
  - docker

script:
  - docker build -t <docker_username>/travis_ci .
  - docker images <docker_username>/travis_ci

before_deploy:
  - docker login -u <docker_username> -p <password>

deploy:
  provider: script
  script: docker push <docker_username>/travis_ci
  on:
    branch: master
